language: elixir

cache:
  directories:
    - ~/.hex
    - ~/.mix
    - deps

elixir:
  - 1.6

otp_release:
  - 19.3
  - 20.0

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

script:
  - mix test
